apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: statefulapp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: stateful
    repoURL: https://github.com/pedavea2/azure.git
    targetRevision: HEAD
